# Generated by Django 2.2.11 on 2020-05-02 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('rid', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='预约id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成的时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='改变状态的时间')),
                ('reservation_time', models.DateTimeField(verbose_name='预约时间')),
                ('status', models.IntegerField(choices=[('0', '已关闭'), ('1', '已生成')], default=1, verbose_name='预约时间点状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True, verbose_name='用户是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_log_time', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('avatar_url', models.URLField()),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('country', models.CharField(max_length=20, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('tid', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='订单id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成订单时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='订单状态更新时间')),
                ('status', models.IntegerField(choices=[('0', '已取消'), ('1', '已预约'), ('2', '已支付'), ('3', '已完成')], verbose_name='订单状态')),
                ('price', models.IntegerField(verbose_name='订单金额')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='手机号')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='详细问题')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Reservation', verbose_name='预约表id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.UserInfo', verbose_name='预约用户id')),
            ],
        ),
    ]
