# Generated by Django 2.2.11 on 2020-05-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.BigIntegerField(choices=[('0', '已取消'), ('1', '已预约'), ('2', '已支付'), ('3', '已完成')], verbose_name='订单状态'),
        ),
    ]
