# Generated by Django 2.2.11 on 2020-05-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200502_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('0', '已取消'), ('1', '已预约'), ('2', '已支付'), ('3', '已完成')], max_length=1, verbose_name='订单状态'),
        ),
    ]
