# Generated by Django 2.2.11 on 2020-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200503_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('0', '已取消'), ('1', '待支付'), ('2', '已支付'), ('3', '已完成')], max_length=1, verbose_name='订单状态'),
        ),
    ]
